### PR TITLE
update some snippets from getmdl.io

### PR DESCRIPTION
**Pull request by smkamranqadri**
i would like to contribute in this package as i am using this package and there are snippets which are missing, thx.

### CODE REVIEW

**Comment by ahmadbilal** [comment]
thank you for your contribution. :)

**Comment by smkamranqadri** [comment]
Any time

**Comment by smkamranqadri** [comment]
Please publish the package so every one can get benefits out of it.

**Comment by ahmadbilal** [comment]
Should be published now. Please check again. Thanks!

**Comment by smkamranqadri** [comment]
Done. thx

**Pull request merged**
